language: php

before_script:
  - if [ -n "$GIT_HUB_TOKEN" ]; then composer config -g github-oauth.github.com "$GIT_HUB_TOKEN"; fi;
  - composer install
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;
  - "./test/prism.sh &"
  - sleep 60

script:
  - "vendor/bin/phpunit test --filter test*"

after_success:
  - bash <(curl -s https://codecov.io/bash)

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - dependencies=lowest
  - dependencies=highest

notifications:
  slack:
    if: branch = master
    on_success: never
    on_failure: change
    rooms:
      - secure: R9JCklL/+TTher3FyJ2h3jFCnxkMHF8T9FszoOLfZeIR1hNADN9wqsLu8bItuKr3hcLzzR/1dG/rDQnHH2TmYuen0VSXBNoN/D1qGJPGayRrsAAUQXrcI9YVwdGwIcuoszM1GYFh3kQRf7RztUJeIw4P6Hl5WQyQC27UmflHK/M=
